// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoOxBK-sdIfdXHuwyyNbg7Kqpx6VcLvw8',
    appId: '1:366957709927:web:3c7a4a81cce4cbed8e62c2',
    messagingSenderId: '366957709927',
    projectId: 'blockbuster-hunt-e3910',
    authDomain: 'blockbuster-hunt-e3910.firebaseapp.com',
    storageBucket: 'blockbuster-hunt-e3910.firebasestorage.app',
    measurementId: 'G-DNBQPB9ME0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3UmzZO0_mFXgUJuykOdsPtgD5gI3SWh8',
    appId: '1:366957709927:android:ff3f24b9935463308e62c2',
    messagingSenderId: '366957709927',
    projectId: 'blockbuster-hunt-e3910',
    storageBucket: 'blockbuster-hunt-e3910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddd7hbkPosOY_1UAhUpCrbHbFSlNkLGo',
    appId: '1:366957709927:ios:d6084dab490a977f8e62c2',
    messagingSenderId: '366957709927',
    projectId: 'blockbuster-hunt-e3910',
    storageBucket: 'blockbuster-hunt-e3910.firebasestorage.app',
    iosBundleId: 'com.example.blockbusterHunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBddd7hbkPosOY_1UAhUpCrbHbFSlNkLGo',
    appId: '1:366957709927:ios:d6084dab490a977f8e62c2',
    messagingSenderId: '366957709927',
    projectId: 'blockbuster-hunt-e3910',
    storageBucket: 'blockbuster-hunt-e3910.firebasestorage.app',
    iosBundleId: 'com.example.blockbusterHunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoOxBK-sdIfdXHuwyyNbg7Kqpx6VcLvw8',
    appId: '1:366957709927:web:c9661e3a22f2b6c68e62c2',
    messagingSenderId: '366957709927',
    projectId: 'blockbuster-hunt-e3910',
    authDomain: 'blockbuster-hunt-e3910.firebaseapp.com',
    storageBucket: 'blockbuster-hunt-e3910.firebasestorage.app',
    measurementId: 'G-XZ8KKS9ZCX',
  );
}
